apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cojocloud/argocd-eks-terraform-workflow.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: flask-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
